node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Function.listen (/mnt/c/Users/nprks/IdeaProjects/n8prks-2.8_nodeAppWithLogDir/package/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/mnt/c/Users/nprks/IdeaProjects/n8prks-2.8_nodeAppWithLogDir/package/server.js:52:5)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v21.5.0
app listening on port 3000!
-----------------------------
successfully set the following environment variables: 
APP_ENV - dev
DB_USER - myuser
DB_PWD - mysecret
-----------------------------
successfully set LOG_DIR environment variable. Writing logs into /mnt/c/Users/nprks/IdeaProjects/n8prks-2.8_nodeAppWithLogDir/log_dir
-----------------------------
Logging into the app.log file
Application started successfully using all the provided environment variables
Node app will listen for any incoming connections
This is the end of log entries
-----------------------------
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Function.listen (/mnt/c/Users/nprks/IdeaProjects/n8prks-2.8_nodeAppWithLogDir/package/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/mnt/c/Users/nprks/IdeaProjects/n8prks-2.8_nodeAppWithLogDir/package/server.js:52:5)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v21.5.0
